### ISSUE TITLE
.explain Application/octet Mime Type Error

### ISSUE THREAD

**Issue by mrjarbenne** [Blobfolio/blob-mimes#2]
I've added the mime type in a functionality plugin to be allowed (hence it passing the WordPress test). The rest is failing for some reason. Perhaps you can assist me in reading the output: is the server mistaking the file type as a zip file? 

A .explain file is the saved file type for the app http://explaineverything.com

Let me know if I can provide further details. 

Here's the output from the plugin:

> ======================================================================
>                                 RESULT                                
> ======================================================================
> The following error(s) were found:
> — The file type is not allowed.
> 
> 
> ======================================================================
>                                 TESTS                                 
> ======================================================================
> 
> 
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
>                               WORDPRESS                               
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
> PASS:          TRUE
> TEST:          [ext] explain
>                [type] application/octet-stream
> RESULT:        [pass] The file extension is allowed.
> 
> 
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
>                                FILEINFO                               
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
> PASS:          FALSE
> TEST:          [type] application/zip
>                [match alias] FALSE
>                [allowed explicit] FALSE
>                [allowed alias] FALSE
> RESULT:        [error] The file type is not allowed.
> 
> 
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
>                               BLOB-MIMES                              
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
> PASS:          FALSE
> TEST:          [name] grade-8-battleship.explain
>                [type] FALSE
>                [ext] FALSE
>                [renamed] FALSE
> RESULT:        [error] The file type is not allowed.
> 
> 
> ======================================================================
>                              ENVIRONMENT                              
> ======================================================================
> 
> 
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
>                               WORDPRESS                               
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
> VERSION:       4.7.5
> PLUGINS:       debug-bar [0.9]
>                debug-bar-actions-and-filters-addon [1.5.2]
>                instagram-feed-pro [2.4.1]
> THEME:         twentyfifteen [1.7]
> 
> 
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
>                                  PHP                                  
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
> VERSION:       5.5.30-1~dotdeb+7.1
> OS:            Linux commons.hwdsb.on.ca
>                4.8.3-x86_64-linode76 #1 SMP Thu Oct 20 19:05:39 EDT
>                2016 x86_64
> EXTENSIONS:    Core; PDO; Phar; Reflection; SPL;
>                SimpleXML; Zend OPcache; bcmath; bz2; calendar;
>                cgi-fcgi; ctype; curl; date; dba; dom; ereg; exif;
>                fileinfo; filter; ftp; gd; gettext; hash; http; iconv;
>                imagick; json; libxml; mbstring; mcrypt; memcached;
>                mhash; mysql; mysqli; mysqlnd; openssl; pcre;
>                pdo_mysql; posix; readline; redis; session; shmop;
>                soap; sockets; ssh2; standard; sysvmsg; sysvsem;
>                sysvshm; tokenizer; wddx; xml; xmlreader; xmlwriter;
>                xsl; zip; zlib

**Comment by joshstoik1** [comment]
In the case of your WordPress install, the chain is something like this:

1. WordPress looks at the name, decides the file is an `application/octet-stream` type;
2. WordPress asks PHP (via `fileinfo.so`), which says it is `application/zip`;
3. Because PHP's answer begins `application/*`, WordPress checks to see whether `application/zip` files have been also whitelisted;

At this point normally `Lord of the Files` would run tests to see if the extension and type make sense together, however it has no entries for `.explain` files so can't do that.

To that end, would you please attach an example `.explain` file? There is no official IANA media type for that format, but I can examine its structure and come up with some useful aliases at least. Once the db is updated, it should allow you to upload those files (so long as you keep the extension whitelisted).

**Comment by mrjarbenne** [comment]
Thanks so much for that. Here's an example file: https://cloudup.com/cmR89IaPFPk

**Comment by joshstoik1** [comment]
Thanks for supplying an example!  It looks like `.explain` files are indeed Zip archives.  Until an official media type is registered, that's probably how most Magic MIME libraries will see them.

I added a manual entry for the format and recompiled the databases. Version `0.5.3-0` of the WP plugin contains that update. It has been pushed to WP, but might not show up as an available update within your site for another 15-30 minutes or so.

Let me know if that fixes the issue for you once you're able to update.
