### ISSUE TITLE
Re-license to LGPL, MIT, BSD or similar?

### ISSUE THREAD

**Issue by motin** [Blobfolio/blob-mimes#3]
I am a long-time open source contributor and promoter, but the use of GPL for blob-mimes is making it impossible for me to use or contribute to its development since not only do I do open source, I also sell my time as a programmer for other companies, and in those projects GPL is not an option. 

Will you consider re-licensing this to LGPL, MIT or BSD or similar?

**Comment by joshstoik1** [comment]
My apologies, the GPL license was a legacy of an earlier incarnation of the library, something I forgot to update. :)

`blob-mimes` has been relicensed under [WTFPL](http://www.wtfpl.net), so you shouldn't run into any issues with its bones.

The various source data this library draws from each have their own licenses, but they're all more permissive than GPL. The quickest way to locate those sources is at the [top of the build file](https://github.com/Blobfolio/blob-mimes/blob/master/build/build.php#L24).
