### ISSUE TITLE
Type substitution

### ISSUE THREAD

**Issue by dmitrach** [Blobfolio/blob-mimes#6]
Does not cope with type 'application'.
By and large, the reading comes from the file name.
The package has many dependencies, but the same result could be achieved with standard libraries.

/*My test*/
array(
				static::ASSETS . 'opera-stable_56.0.3051.43_amd64.deb',
				array(
					'dirname'=>rtrim(static::ASSETS, '/'),
					'basename'=>'opera-stable_56.0.3051.43_amd64.deb',
					'extension'=>'deb',
					'filename'=>'opera-stable_56.0.3051.43_amd64',
					'path'=>static::ASSETS . 'opera-stable_56.0.3051.43_amd64.deb',
					'mime'=>'application/vnd.debian.binary-package',
				),
				null,
			),
			array(
				static::ASSETS . 'russian_ru_language_pack_thunderbird-52.0-tb.xpi',
				array(
					'dirname'=>rtrim(static::ASSETS, '/'),
					'basename'=>'russian_ru_language_pack_thunderbird-52.0-tb.xpi',
					'extension'=>'xpi',
					'filename'=>'russian_ru_language_pack_thunderbird-52.0-tb',
					'path'=>static::ASSETS . 'russian_ru_language_pack_thunderbird-52.0-tb.xpi',
					'mime'=>'application/x-xpinstall',
				),
				null,
			),
			array(
				static::ASSETS . '1',
				array(
					'dirname'=>rtrim(static::ASSETS, '/'),
					'basename'=>'1',
					'extension'=>'jpeg',
					'filename'=>'1',
					'path'=>static::ASSETS . '1',
					'mime'=>'image/jpeg',
				),
				null,
			),
			array(
				static::ASSETS . 'header.blade.php',
				array(
					'dirname'=>rtrim(static::ASSETS, '/'),
					'basename'=>'header.blade.php',
					'extension'=>'php',
					'filename'=>'header.blade',
					'path'=>static::ASSETS . 'header.blade.php',
					'mime'=>'application/x-php',
				),
				null,
			),
			array(
				static::ASSETS . 'Chamelephon_by_N13.apk',
				array(
					'dirname'=>rtrim(static::ASSETS, '/'),
					'basename'=>'Chamelephon_by_N13.apk',
					'extension'=>'apk',
					'filename'=>'Chamelephon_by_N13',
					'path'=>static::ASSETS . 'Chamelephon_by_N13.apk',
					'mime'=>'application/vnd.android.package-archive',
				),
				null,
			),
			array(
				static::ASSETS . 'altstoneby.sql',
				array(
					'dirname'=>rtrim(static::ASSETS, '/'),
					'basename'=>'altstoneby.sql',
					'extension'=>'sql',
					'filename'=>'altstoneby',
					'path'=>static::ASSETS . 'altstoneby.sql',
					'mime'=>'application/sql',
				),
				null,
			),
			array(
				static::ASSETS . 'altstoneby.sql',
				array(
					'dirname'=>rtrim(static::ASSETS, '/'),
					'basename'=>'altstoneby.sql',
					'extension'=>'sql',
					'filename'=>'altstoneby',
					'path'=>static::ASSETS . 'altstoneby.sql',
					'mime'=>'application/sql',
				),
				null,
			),
			array(
				static::ASSETS . 'sql.sql',
				array(
					'dirname'=>rtrim(static::ASSETS, '/'),
					'basename'=>'sql.sql',
					'extension'=>'php',
					'filename'=>'sql',
					'path'=>static::ASSETS . 'sql.sql',
					'mime'=>'application/x-php',
				),
				null,
			),
			array(
				static::ASSETS . 'style.css',
				array(
					'dirname'=>rtrim(static::ASSETS, '/'),
					'basename'=>'style.css',
					'extension'=>'css',
					'filename'=>'style',
					'path'=>static::ASSETS . 'style.css',
					'mime'=>'application/x-php',
				),
				null,
			),
			array(
				static::ASSETS . 'sql',
				array(
					'dirname'=>rtrim(static::ASSETS, '/'),
					'basename'=>'sql',
					'extension'=>'php',
					'filename'=>'sql',
					'path'=>static::ASSETS . 'sql',
					'mime'=>'application/x-php',
				),
				null,
			),
			array(
				static::ASSETS . 'style',
				array(
					'dirname'=>rtrim(static::ASSETS, '/'),
					'basename'=>'style',
					'extension'=>'php',
					'filename'=>'style',
					'path'=>static::ASSETS . 'style',
					'mime'=>'application/x-php',
				),
				null,
			),
			array(
				static::ASSETS . 'PAP5044DUO_1.0.49.rar',
				array(
					'dirname'=>rtrim(static::ASSETS, '/'),
					'basename'=>'PAP5044DUO_1.0.49.rar',
					'extension'=>'rar',
					'filename'=>'PAP5044DUO_1.0.49',
					'path'=>static::ASSETS . 'PAP5044DUO_1.0.49.rar',
					'mime'=>'application/vnd.rar',
				),
				null,
			),
			array(
				static::ASSETS . 'Облако Mail.Ru.apk',
				array(
					'dirname'=>rtrim(static::ASSETS, '/'),
					'basename'=>'Облако Mail.Ru.apk',
					'extension'=>'zip',
					'filename'=>'Облако Mail.Ru',
					'path'=>static::ASSETS . 'Облако Mail.Ru.apk',
					'mime'=>'application/vnd.rar',
				),
				null,
			),
/*=============================*/

There were 5 failures:

1) mime_tests::test_finfo with data set #8 ('/home/dios/Загрузки/test/vend...ql.sql', array('/home/dios/Загрузки/test/vend...assets', 'sql.sql', 'php', 'sql', '/home/dios/Загрузки/test/vend...ql.sql', 'application/x-php'), null)
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     'dirname' => '/home/dios/Загрузки/test/vend...assets'
     'basename' => 'sql.sql'
-    'extension' => 'php'
+    'extension' => 'sql'
     'filename' => 'sql'
     'path' => '/home/dios/Загрузки/test/vend...ql.sql'
-    'mime' => 'application/x-php'
+    'mime' => 'application/sql'
 )

/home/dios/Загрузки/test/vendor/blobfolio/blob-mimes/tests/test-mime.php:74

2) mime_tests::test_finfo with data set #9 ('/home/dios/Загрузки/test/vend...le.css', array('/home/dios/Загрузки/test/vend...assets', 'style.css', 'css', 'style', '/home/dios/Загрузки/test/vend...le.css', 'application/x-php'), null)
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
     'path' => '/home/dios/Загрузки/test/vend...le.css'
-    'mime' => 'application/x-php'
+    'mime' => 'text/css'
 )

/home/dios/Загрузки/test/vendor/blobfolio/blob-mimes/tests/test-mime.php:74

3) mime_tests::test_finfo with data set #10 ('/home/dios/Загрузки/test/vend...ts/sql', array('/home/dios/Загрузки/test/vend...assets', 'sql', 'php', 'sql', '/home/dios/Загрузки/test/vend...ts/sql', 'application/x-php'), null)
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     'dirname' => '/home/dios/Загрузки/test/vend...assets'
     'basename' => 'sql'
-    'extension' => 'php'
+    'extension' => 'txt'
     'filename' => 'sql'
     'path' => '/home/dios/Загрузки/test/vend...ts/sql'
-    'mime' => 'application/x-php'
+    'mime' => 'text/plain'
 )

/home/dios/Загрузки/test/vendor/blobfolio/blob-mimes/tests/test-mime.php:74

4) mime_tests::test_finfo with data set #11 ('/home/dios/Загрузки/test/vend.../style', array('/home/dios/Загрузки/test/vend...assets', 'style', 'php', 'style', '/home/dios/Загрузки/test/vend.../style', 'application/x-php'), null)
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
     'path' => '/home/dios/Загрузки/test/vend.../style'
-    'mime' => 'application/x-php'
+    'mime' => 'text/x-php'
 )

/home/dios/Загрузки/test/vendor/blobfolio/blob-mimes/tests/test-mime.php:74

5) mime_tests::test_finfo with data set #13 ('/home/dios/Загрузки/test/vend...Ru.apk', array('/home/dios/Загрузки/test/vend...assets', 'Облако Mail.Ru.apk', 'zip', 'Облако Mail.Ru', '/home/dios/Загрузки/test/vend...Ru.apk', 'application/vnd.rar'), null)
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
     'path' => '/home/dios/Загрузки/test/vend...Ru.apk'
-    'mime' => 'application/vnd.rar'
+    'mime' => 'application/zip'
 )

**Comment by joshstoik1** [comment]
Thanks @dios-oleg, but except for a few special edge cases, this library does not perform its own type detection. Content-based sniffing is done via `fileinfo.so` (if installed), otherwise it falls back to simple name-based checks.

The main purpose of the `blob-mimes` wrapper is to deal with _MIME aliases_. File formats typically begin life with unofficial media type associations — which might vary by browser, software, etc. — before an official IANA registration is submitted. Depending on the version of `fileinfo.so` installed on a given server, the MIME type returned could be any of a dozen different values. This library will convert aliases to the official type in such cases, making detection more consistent across different environments.

For example, if you were to feed a `WOFF` font file to `fileinfo.so` directly, the extension might return `application/x-font-woff`, `application/font-woff`, `application/woff`, `font/x-woff`, `font/woff`, etc. When using the `blob-mimes` wrapper, the MIME type will always be the official IANA media type `font/woff`.
